#define CMD_error -1
#define CMD_none   0
#define CMD_close  1
#define CMD_create 2
#define CMD_delete 3
#define CMD_dir    4
#define CMD_login  5
#define CMD_logout 6
#define CMD_open   7
#define CMD_read   8
#define CMD_write  9