fcfs : 
	gcc src/proc.c src/procqueue.c src/cpu.c FCFS.c -o FCFS
sjf  :
	gcc src/proc.c src/procqueue.c src/cpu.c SJF.c -o SJF
hrrn  :
		gcc src/proc.c src/procqueue.c src/cpu.c HRRN.c -o HRRN

clean : 
	rm -f FCFS SJF HRRN